### ISSUE TITLE
the label shape is out of bounds

### ISSUE THREAD

**Issue by maryhh** [miraclewkf/FocalLoss-MXNet#2]
![default](https://user-images.githubusercontent.com/26423386/53399797-94e86e80-39e7-11e9-9ad8-906082b25490.png)
i used the focal loss and metric ,but I have a problem.it seems like the label shape is out of bounds.but when i use softmax loss ,it's ok. do you know the reason?

**Comment by maryhh** [comment]
softmaxloss output  like this:
![default](https://user-images.githubusercontent.com/26423386/53400400-b85fe900-39e8-11e9-8f5f-6345bca1d3f8.png)

**Comment by mingzhang96** [comment]
@maryhh Have you solved this problem?
